default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  DATABASE_DB: "database name"
  DATABASE_PASSWORD: "database username"
  DATABASE_USERNAME: "database password"
  # Mailer configuration
  SMTP_ADDRESS: "smtp email address"
  SMTP_DOMAIN: "smtp email domain"
  SMTP_PORT: "587"
  SMTP_USERNAME: "smtp email username"
  SMTP_PASSWORD: "smtp email password"
  # GeoCoder configuration (developer.here.com)
  HERE_API_KEY: "your here api key"
  SECRET_KEY_BASE: "secret_key_base"
  # Omniauth credentials
  OMNIAUTH_FACEBOOK_APP_ID: 'fb_app_id'
  OMNIAUTH_FACEBOOK_APP_SECRET: 'fb_app_secret'
  OMNIAUTH_GOOGLE_CLIENT_ID: 'google_client_id'
  OMNIAUTH_GOOGLE_CLIENT_SECRET: 'google_client_secret'

development:
  <<: *default

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
